### ISSUE TITLE
Export libdl?

### ISSUE THREAD

**Issue by Brunni** [bilke/conan-vtk#3]
Hi, I'm not sure, if I'm right, but I had some compilation issues in my project, where I think they could/should be fixed in the conanfile.py of vtk.

The error was
`libdl.so.2: error adding symbols: DSO missing from command line`

I could fix this, when I linked my executable agains dl using target_link_libraries.
I guess, this could be fixed by changing package_info of vtk to include "dl" for linux.

EDIT: Perhaps it is comparable to this case with pthread?
https://github.com/Brunni/conan-g3log/commit/37f891757d4730ffda592d254c632a061e6302ae

**Comment by bilke** [comment]
This could have other reasons, see the following links:

- http://stackoverflow.com/questions/9934549/very-strange-linker-behavior
- http://stackoverflow.com/questions/23141575/undefined-reference-to-symbol-dso-missing-from-command-line

As I am using my VTK package on Linux too without problems I suggest you to just link to `CMAKE_DL_LIBS` as pointed out in [this SO answer](http://stackoverflow.com/a/8243870/80480).

**Comment by Brunni** [comment]
Thank you very much. CMAKE_DL_LIBS looks like a correct an platform independent solution.
