### ISSUE TITLE
How to use this repo to get VTK-build?

### ISSUE THREAD

**Issue by artzers** [bilke/conan-vtk#8]
Hello, I am new to conan. I want to use conan to manager the 3rd library for C++ project. However  I cannot find VTK8.2( compatible with qt5 ) package in conan-center, conan-transit, conan-community and bincrafters. There is only vtk7.1@bilke.  
I also download your codes and have a try. I have tried `conan install` or ` conan build` but failed. Could you please tell me how to get the vtk8.2( compatible with qt5 ) build using your conan codes? Many thanks.

**Comment by bilke** [comment]
You need add my remote:

```
conan remote add ogs https://ogs.jfrog.io/ogs/api/conan/conan
```

A `conanfile.txt` could look like this:

```
[requires]
vtk/8.2.0@bilke/stable

[options]
vtk:qt=True
```

Then `conan install`.
